### ISSUE TITLE
./gradle/wrapper/gradle-wrapper.jar missing from repository

### ISSUE THREAD

**Issue by powerlord** [ArchipelagoMW/Archipelago.MultiClient.Java#1]
This jar is used by gradlew.bat on Windows and gradlew on Linux to download Gradle itself to do compilation.

This file isn't present because the gradle directory is in the .gitignore file.

I would fix this in a pull request, but this jar is also the file that specifies which version of Gradle to use.

**Comment by KonoTyran** [comment]
my bad, there ya go
